import pool from '../config/db.js';

export const seedAdministration = async () => {
    const members = [
        // ── DIRECTOR ──────────────────────────────────────────────────────────
        {
            id: 'director',
            name: 'Brig Ajit Kumar Borah, VSM (Retd)',
            role: null,
            designation: 'Director, AIN Guwahati',
            section: 'director',
            imageUrl: '/uploads/images/about/director.jpeg',
            qualification: 'Brigadier (Retd), Indian Army',
            experience: '35+ Years in Operations & Administration',
            specialization: 'Strategic Operations, Crisis Management, Institutional Governance',
            quote: 'Discipline, execution excellence, and welfare form the foundation of our institution.',
            description: 'Brig Ajit Kumar Borah, VSM (Retd) leads the administrative, financial, and strategic direction of the Army Institute of Nursing, Guwahati. With a highly decorated military career, he oversees infrastructure projects, coordinates with government/defense authorities, and ensures that the college runs with military-grade precision and efficiency.',
            sortOrder: 0,
            isLinked: true,
            staffId: 'STF-1775881000101'
        },

        // ── PRINCIPAL ─────────────────────────────────────────────────────────
        {
            id: 'principal',
            name: 'Prof. Kabita Baishya',
            role: null,
            designation: 'Principal, AIN Guwahati',
            section: 'principal',
            imageUrl: '/uploads/images/about/principal.jpeg',
            qualification: 'M.Sc Nursing, Ph.D Scholar',
            experience: '25+ Years in Nursing Education',
            specialization: 'Medical Surgical Nursing, Academic Governance',
            quote: 'Our goal is to shape nurses who are not just clinically competent but are equipped with moral values and a spirit of selfless service.',
            description: 'Prof. Kabita Baishya is the academic lead of AIN Guwahati. She is responsible for curricular design, faculty development, affiliation and compliance audits, and maintaining the highest standard of classroom and clinical instruction. Under her leadership, the institute has maintained a record of 100% academic pass rates and national distinctions.',
            sortOrder: 1,
            isLinked: true,
            staffId: 'STF-1775881000001'
        },

        // ── REGISTRAR ─────────────────────────────────────────────────────────
        {
            id: 'registrar',
            name: 'Col Jyoti Prasad Saikia (Retd)',
            role: null,
            designation: 'Registrar & HOA, AIN Guwahati',
            section: 'registrar',
            imageUrl: '/uploads/images/about/registrar.jpeg',
            qualification: 'Colonel (Retd), Indian Army',
            experience: '30+ Years in Administration & Logistics',
            specialization: 'Security, Human Resources, Financial Operations',
            quote: 'Providing a secure, seamless, and highly supportive ecosystem for our campus community.',
            description: 'Col Jyoti Prasad Saikia (Retd) manages the day-to-day administrative operations, estate security, accounts, admissions processing, and non-teaching personnel. He ensures that campus resources, student hostels, transport services, and technological infrastructure are optimized to support the core academic and medical goals of AIN.',
            sortOrder: 2,
            isLinked: true,
            staffId: 'STF-1775881000102'
        },

        // ── ACADEMIC STAFF ────────────────────────────────────────────────────
        {
            id: 'acad-001',
            name: 'Dr. Meena Sharma',
            role: 'Associate Vice Principal',
            designation: 'Ph.D Nursing, M.Sc Nursing',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'Ph.D Nursing, M.Sc Nursing',
            experience: '18 Years in Nursing Education',
            specialization: 'Obstetrics & Gynaecological Nursing',
            quote: 'Excellence in nursing begins with excellence in character.',
            description: 'Dr. Meena Sharma oversees curriculum implementation and faculty coordination. She has published several research papers in maternal and child health nursing.',
            sortOrder: 10,
            isLinked: false,
            staffId: null
        },
        {
            id: 'acad-002',
            name: 'Mrs. Priya Devi',
            role: 'Associate Professor',
            designation: 'M.Sc Nursing (Medical-Surgical)',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'M.Sc Nursing (Medical-Surgical)',
            experience: '14 Years in Clinical Teaching',
            specialization: 'Medical Surgical Nursing, Critical Care',
            quote: 'Every patient is a teacher; every interaction is a lesson.',
            description: 'Mrs. Priya Devi specialises in critical care nursing and leads the Medical Surgical department at AIN.',
            sortOrder: 11,
            isLinked: false,
            staffId: null
        },
        {
            id: 'acad-003',
            name: 'Mrs. Rupa Gogoi',
            role: 'Associate Professor',
            designation: 'M.Sc Nursing (Community Health)',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'M.Sc Nursing (Community Health)',
            experience: '12 Years in Community Health Nursing',
            specialization: 'Community Health, Public Health Nursing',
            quote: 'Health is a community responsibility — nurses are its champions.',
            description: 'Mrs. Rupa Gogoi leads community health outreach programs and coordinates field practicals for final-year nursing students.',
            sortOrder: 12,
            isLinked: false,
            staffId: null
        },
        {
            id: 'acad-004',
            name: 'Mrs. Anita Bora',
            role: 'Assistant Professor',
            designation: 'M.Sc Nursing (Paediatrics)',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'M.Sc Nursing (Paediatrics)',
            experience: '10 Years in Teaching & Clinical Practice',
            specialization: 'Paediatric Nursing, Child Health',
            quote: 'Caring for children is the most rewarding form of nursing practice.',
            description: 'Mrs. Anita Bora teaches paediatric nursing and supervises students at the Base Hospital Paediatric Ward.',
            sortOrder: 13,
            isLinked: false,
            staffId: null
        },
        {
            id: 'acad-005',
            name: 'Ms. Rekha Nath',
            role: 'Assistant Professor',
            designation: 'M.Sc Nursing (Psychiatric)',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'M.Sc Nursing (Psychiatric)',
            experience: '8 Years in Mental Health Nursing',
            specialization: 'Psychiatric Nursing, Mental Health',
            quote: 'Mental health care is as vital as physical care — we must treat the whole person.',
            description: 'Ms. Rekha Nath teaches psychiatric nursing and conducts awareness workshops on mental health at Base Hospital.',
            sortOrder: 14,
            isLinked: false,
            staffId: null
        },
        {
            id: 'acad-006',
            name: 'Mrs. Sunita Kalita',
            role: 'Tutor',
            designation: 'B.Sc Nursing, M.Sc Nursing (Pursuing)',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'B.Sc Nursing, M.Sc Nursing (Pursuing)',
            experience: '5 Years in Nursing Education',
            specialization: 'Fundamentals of Nursing, Basic Life Support',
            quote: 'Strong fundamentals create confident nurses.',
            description: 'Mrs. Sunita Kalita teaches foundational nursing skills and organises clinical simulation labs for first-year students.',
            sortOrder: 15,
            isLinked: false,
            staffId: null
        },
        {
            id: 'acad-007',
            name: 'Mr. Bipul Das',
            role: 'Tutor',
            designation: 'B.Sc Nursing',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'B.Sc Nursing',
            experience: '4 Years in Nursing Education',
            specialization: 'Anatomy & Physiology, Clinical Skills',
            quote: 'Understanding the human body is the first step to healing it.',
            description: 'Mr. Bipul Das teaches anatomy, physiology, and assists in clinical laboratory practicals.',
            sortOrder: 16,
            isLinked: false,
            staffId: null
        },
        {
            id: 'acad-008',
            name: 'Mrs. Jayashree Baruah',
            role: 'Computer Instructor',
            designation: 'MCA, B.Sc Computer Science',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'MCA, B.Sc Computer Science',
            experience: '9 Years in IT Education',
            specialization: 'Healthcare IT, Computer Applications, Data Management',
            quote: 'Technology is the future of healthcare — nurses must be digitally fluent.',
            description: 'Mrs. Jayashree Baruah manages the computer lab and teaches health informatics, computer applications, and digital documentation to nursing students.',
            sortOrder: 17,
            isLinked: false,
            staffId: null
        },
        {
            id: 'acad-009',
            name: 'Mr. Rajan Kumar',
            role: 'ITI Supervisor / Network Administrator',
            designation: 'B.Tech (IT), CCNA Certified',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'B.Tech (IT), CCNA Certified',
            experience: '7 Years in Network Administration',
            specialization: 'Network Infrastructure, IT Security, System Administration',
            quote: 'A connected campus is a productive campus.',
            description: 'Mr. Rajan Kumar manages the campus IT infrastructure, maintains the LAN/WAN network, and supports digital learning tools used by faculty and students.',
            sortOrder: 18,
            isLinked: false,
            staffId: null
        },
        {
            id: 'acad-010',
            name: 'Mrs. Pallabi Dutta',
            role: 'Lab Computer Lab Assistant',
            designation: 'B.Sc Computer Science',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'B.Sc Computer Science',
            experience: '3 Years in Lab Management',
            specialization: 'Computer Lab Management, IT Support',
            quote: 'A well-maintained lab is the backbone of practical learning.',
            description: 'Mrs. Pallabi Dutta assists students in computer lab sessions and maintains all lab equipment and software.',
            sortOrder: 19,
            isLinked: false,
            staffId: null
        },
        {
            id: 'acad-011',
            name: 'Mr. Hemanta Deka',
            role: 'Assistant Librarian',
            designation: 'M.Lib Information Science',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'M.Lib Information Science',
            experience: '6 Years in Library Services',
            specialization: 'Digital Library, Cataloguing, Reference Services',
            quote: 'A good library is a bridge between the student and the world of knowledge.',
            description: 'Mr. Hemanta Deka manages cataloguing, digital library access, and reference services, ensuring students have timely access to academic resources.',
            sortOrder: 20,
            isLinked: false,
            staffId: null
        },
        {
            id: 'acad-012',
            name: 'Ms. Barnali Das',
            role: 'Library Attendent',
            designation: 'B.Lib Science',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'B.Lib Science',
            experience: '4 Years',
            specialization: 'Book Issuing, Library Maintenance',
            quote: '',
            description: 'Ms. Barnali Das assists students in locating books and manages the daily issue and return of library resources.',
            sortOrder: 21,
            isLinked: false,
            staffId: null
        },
        {
            id: 'acad-013',
            name: 'Mr. Sanjib Borah',
            role: 'Laboratory Attendent',
            designation: 'B.Sc (Life Sciences)',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'B.Sc (Life Sciences)',
            experience: '5 Years in Lab Assistance',
            specialization: 'Lab Equipment Maintenance, Specimen Preparation',
            quote: '',
            description: 'Mr. Sanjib Borah ensures all nursing skill labs are properly equipped, maintained, and ready for student practicals.',
            sortOrder: 22,
            isLinked: false,
            staffId: null
        },
        {
            id: 'acad-014',
            name: 'Mr. Dulal Choudhury',
            role: 'Lab Assistant',
            designation: 'ITI Certificate',
            section: 'academic-staff',
            imageUrl: null,
            qualification: 'ITI Certificate',
            experience: '3 Years',
            specialization: 'Equipment Setup, Lab Support',
            quote: '',
            description: 'Mr. Dulal Choudhury supports faculty and students during lab sessions, prepares equipment, and maintains laboratory cleanliness and safety.',
            sortOrder: 23,
            isLinked: false,
            staffId: null
        },

        // ── ADMINISTRATIVE STAFF ───────────────────────────────────────────────
        {
            id: 'admin-001',
            name: 'Mr. Rajib Saikia',
            role: 'Office Superintendent / Head Clerk',
            designation: 'B.Com, PG Diploma in Administration',
            section: 'admin-staff',
            imageUrl: null,
            qualification: 'B.Com, Post Graduate Diploma in Administration',
            experience: '20 Years in Administrative Services',
            specialization: 'Office Management, Record Keeping, Government Correspondence',
            quote: 'Efficient administration is the silent engine behind every successful institution.',
            description: 'Mr. Rajib Saikia manages the institute\'s administrative office, oversees clerical staff, and ensures all official communications, records, and documentation are maintained with accuracy and timeliness.',
            sortOrder: 30,
            isLinked: false,
            staffId: null
        },
        {
            id: 'admin-002',
            name: 'Mr. Dhiraj Mahanta',
            role: 'Hostel Warden',
            designation: 'B.A, Diploma in Hostel Management',
            section: 'admin-staff',
            imageUrl: null,
            qualification: 'B.A, Diploma in Hostel Management',
            experience: '12 Years in Hostel Administration',
            specialization: 'Student Welfare, Hostel Discipline, Safety Management',
            quote: 'A safe and nurturing hostel environment shapes responsible professionals.',
            description: 'Mr. Dhiraj Mahanta oversees the student hostel facility, ensuring cleanliness, discipline, safety, and the overall well-being of residential students.',
            sortOrder: 31,
            isLinked: false,
            staffId: null
        },
        {
            id: 'admin-003',
            name: 'Mr. Nayan Barua',
            role: 'Accountant',
            designation: 'M.Com, CA Inter',
            section: 'admin-staff',
            imageUrl: null,
            qualification: 'M.Com, CA Inter',
            experience: '15 Years in Financial Administration',
            specialization: 'Budget Management, Audit Compliance, Payroll',
            quote: 'Transparent finances build lasting institutional trust.',
            description: 'Mr. Nayan Barua manages the institute\'s financial records, salary disbursements, fee collections, audit reports, and compliance with government financial regulations.',
            sortOrder: 32,
            isLinked: false,
            staffId: null
        },
        {
            id: 'admin-004',
            name: 'Mr. Bhupen Kalita',
            role: 'Estate Supervisor',
            designation: 'Diploma in Civil Engineering',
            section: 'admin-staff',
            imageUrl: null,
            qualification: 'Diploma in Civil Engineering',
            experience: '10 Years in Estate Management',
            specialization: 'Infrastructure Maintenance, Facility Management',
            quote: 'A well-maintained campus reflects the pride of its people.',
            description: 'Mr. Bhupen Kalita supervises all estate and infrastructure activities including building maintenance, utilities, and campus facilities upkeep.',
            sortOrder: 33,
            isLinked: false,
            staffId: null
        },
        {
            id: 'admin-005',
            name: 'Mrs. Kaberi Gogoi',
            role: 'Receptionist',
            designation: 'B.A, Diploma in Office Management',
            section: 'admin-staff',
            imageUrl: null,
            qualification: 'B.A, Diploma in Office Management',
            experience: '8 Years in Front Office Operations',
            specialization: 'Visitor Management, Communication, Front Desk Operations',
            quote: 'Every visitor deserves a warm and professional welcome.',
            description: 'Mrs. Kaberi Gogoi manages the front office, greets visitors, handles incoming communications, and coordinates appointments for the administrative office.',
            sortOrder: 34,
            isLinked: false,
            staffId: null
        },
        {
            id: 'admin-006',
            name: 'Mr. Pronab Das',
            role: 'PA / Stenographer',
            designation: 'B.A, Shorthand & Typing Certificate',
            section: 'admin-staff',
            imageUrl: null,
            qualification: 'B.A, Shorthand & Typing Certificate',
            experience: '11 Years as Personal Assistant',
            specialization: 'Stenography, Documentation, Scheduling',
            quote: 'Precision in documentation underpins effective leadership.',
            description: 'Mr. Pronab Das serves as Personal Assistant to the Director, managing correspondence, scheduling, and confidential documentation.',
            sortOrder: 35,
            isLinked: false,
            staffId: null
        },
    ];

    console.log('🏛️ Seeding Administration Members...');
    for (const m of members) {
        await pool.query(
            `REPLACE INTO administration_members (id, name, designation, section, role, imageUrl, qualification, experience, specialization, quote, description, sortOrder, isLinked, staffId)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
            [m.id, m.name, m.designation, m.section, m.role, m.imageUrl, m.qualification, m.experience, m.specialization, m.quote, m.description, m.sortOrder, m.isLinked, m.staffId]
        );
    }
    console.log(`✅ Seeded ${members.length} administration members.`);
};
